---
title: "Grafíky"
author: "Jiri Stepan"
date: "12. října 2015"
output: ioslides_presentation
---

## Grafická historie

V prvopočátcích mělo R funkci **plot**, která dle typu předaného objektu kreslila různý grafy. Ale:

- funguje pěkně pro první rychlo náhled.
- jakmile chcete "zhečovat" tak je to peklo
- velmi zmatečná syntaxe, některé parametry se zapisují fo funkce, některé do prostředí grafiky pomocí **par()**
- **DOPORUČUJI OPRAVDU JEN PRO QUICK NÁHLED**

## Grafická historie

- Řada knihoven zavedla mnoho různých jednoúčelových grafů
- Vynikající je **Rcmdr** a **corrplot** pro exploraci dat
- Následně vznikly komplexní grafické knihovny s cílem umožnit pěkné grafy s přehledným zápisem
- Z nich si ukážeme nejrozšířenější **ggplot2**

## Kam kreslíme?

- Rko používá pro namalování grafu aktuálně nastavený výstupní device. 
- Pokud není nastaven, vytvoří si jej. Typicky jako okno
- V RStudiu
- Vlastní device můžeme vytvořir sadou příkazů **png()**, **pdf()** apod.
- device ukončíme pomocí **dev.off**

## Základy ggplot2
- jedná se graphics grammar, popisující
- vezmu dataset 




